# Generated by Django 5.0.4 on 2024-05-02 09:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('realase_date', models.DateField(default=datetime.datetime(2024, 5, 2, 15, 42, 6, 904208))),
                ('ratings', models.CharField(choices=[('1*', '1*'), ('2*', '2*'), ('3*', '3*'), ('4*', '4*'), ('5*', '5*')], max_length=20)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musician.musician')),
            ],
        ),
    ]
